### ISSUE TITLE
Revamp the OAI website to host multiple specifications along with OAS (e.g. Workflows, SLA, etc)

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/Arazzo-Specification#117]
The exit process for new specifications coming out of Special Interest Groups require a home within the OpenAPIs website.

At a minimum, we need to:
- update the specs page - https://spec.openapis.org/
- create a pretty print version of the spec (via #42)

Optionally:
- Update the main website menu options / landing page to advertise multiple specs - https://www.openapis.org/

**Comment by jeremyfiel** [comment]
@frankkilcommins Need to update the text to Arazzo on the homepage

**Comment by dret** [comment]
On 2024-07-31 14:18, Frank Kilcommins wrote:
> @swaldron58 <https://github.com/swaldron58> @dret <https://github.com/dret> in order to close out this issue, I still think we need some enhancements to the navigation menus on the main website.
> Suggested changes:

These look all like very reasonable suggestions. I struggle with the current menu system a fair bit myself. But I have no access to the site and cannot make any changes.

If we want to be ambitious we could embed the hangout video on the "Arazzo intro page", or one of the shorter videos.

- Hangout video (59min): https://www.youtube.com/watch?v=j6Iz99gdkjU
- Frank introducing the spec (7min): https://www.youtube.com/watch?v=C_rkvN9zwKg

One could really embed the video or simply publish a still and link it to the video. We've done that here, for example, and it seems like people like to have the ability to watch a video:

https://www.datamesh-architecture.com/#what-is-data-mesh

**Comment by handrews** [comment]
Note that there's an issue for updating the spec.openapis.org site already: OAI/OpenAPI-Specification#3576

**Comment by swaldron58** [comment]
I did the easy one, the drop downs. I'll get to the rest when I can.

**Comment by frankkilcommins** [comment]
Closing this as _good enough for now_. There's other issues open to adjust based on structural changes to create new dedicated website for specifications as well as larger overhaul of branding site.
