### ISSUE TITLE
Schema object is not defined in the specification

### ISSUE THREAD

**Issue by jeremyfiel** [OAI/Arazzo-Specification#222]
I believe Arazzo should also have a section for `#schema-object` which defines the same as the OpenAPI. 

> The OpenAPI Schema Object [dialect](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.3.3) is defined as requiring the [OAS base vocabulary](https://spec.openapis.org/oas/v3.1.0#fixed-fields-20), in addition to the vocabularies as specified in the JSON Schema draft 2020-12 [general purpose meta-schema](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-8).

The OpenAPI Schema Object dialect for this version of the specification is identified by the URI https://spec.openapis.org/oas/3.1/dialect/base (the “OAS dialect schema id”).

The following properties are taken from the JSON Schema specification but their definitions have been extended by the OAS:

description - [CommonMark syntax](https://spec.commonmark.org/) MAY be used for rich text representation.
format - See [Data Type Formats](https://spec.openapis.org/oas/v3.1.0#dataTypeFormat) for further details. While relying on JSON Schema’s defined formats, the OAS offers a few additional predefined formats.
In addition to the JSON Schema properties comprising the OAS dialect, the Schema Object supports keywords from any other vocabularies, or entirely arbitrary properties.

---

 do not copy this text verbatim because it references the OAS dialect that is not used in Arazzo.  The `description` and `format` keywords seem to follow the same behavior as OAS

**Comment by frankkilcommins** [comment]
We chose not to have a Schema Object so as to steer clear of sub-set/super-set situations.
