### ISSUE TITLE
add code of conduct to meetings

### ISSUE THREAD

**Issue by orubel** [OAI/Arazzo-Specification#263]
Openapi meetings on zoom are required to abide by code of conduct per the meeting notes however Arazzo meetings have no such requirement.

Since @handrews [suggested it will not be added unless we submit a ticket or a template](https://github.com/OAI/Arazzo-Specification/issues/257#issuecomment-2427992547), I am opening a ticket with this issue that this a code of conduct for Zoom  meeting be added/required.

Would suggest using similar format as Openapi.

@handrews also suggested there is a.template for changing meeting? Can someone supply a link to said template? Maybe I can do the pull request once I have this template that @handrews has pointed out exists.

**Comment by handrews** [comment]
@orubel thanks for filing this issue.  I'm not actually sure where it lives, but the OAI/OpenAPI-Specification repo has a GitHub workflow that opens new meeting agenda issues, and I assume that will point to it?  It's in the usual `.github` directory wherever such things live.

**Comment by frankkilcommins** [comment]
For the OpenAPI Spec meetings the template is [here](https://github.com/OAI/OpenAPI-Specification/blob/main/.github/templates/agenda.md) and the github action is [here](https://github.com/OAI/OpenAPI-Specification/blob/main/.github/workflows/agenda.yaml).

We'll work to get the automation in place for Arazzo and in the interim will start adding it manually to the meeting issues. 

Let's use this issue to get that work done. Thanks

**Comment by orubel** [comment]
would you suggest I do a pull request with agenda.yaml/agenda.md or both?

**Comment by orubel** [comment]
Tell you what, I'll download, add templates and agenda.md for now and go from there with the pull request.

I'll see if I can merge the two to create a more concise and consistent meeting agenda with all requirements (specifically code of conduct per ticket)

**Comment by orubel** [comment]
@frankkilcommins There we go. Hopefully that will do it. https://github.com/OAI/Arazzo-Specification/pull/264

Now both meetings have a similar and consistent template. 

Note: It currently states 'daily' meetings; I dont know the agenda but as this is a template, this can be easily changed :)

**Comment by frankkilcommins** [comment]
Thanks @orubel - I'll aim to review it sometime this week.

**Comment by orubel** [comment]
@frankkilcommins oh BTW, I saw that you wanted agenda.md AFTER the fact. I can add after the initial review if you want. Want to make sure I am doing everything right and am conforming first to your way of handling things.

Unless that's more of a pain in the butt... then simply reject this and I'll add it in. :)

**Comment by frankkilcommins** [comment]
no problem. I'll comment back once I get to review and if adjustments are needed then that's OK.

**Comment by frankkilcommins** [comment]
Shall we leave this issue open to also cover adding the action to automate the meeting creation using the template or create a separate issue for the automation part?

**Comment by orubel** [comment]
separate issue. was originally opened for code of conduct.

**Comment by frankkilcommins** [comment]
completed by #264
