### ISSUE TITLE
Meeting: October 23rd, 2024

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/Arazzo-Specification#265]
## Bi-Weekly meetings happen on Wednesdays at 5PM GMT

This agenda gives visibility into discussion topics for the bi-weekly Arazzo meetings. Sharing agenda items in advance allows people to plan to attend meetings where they have an interest in specific topics. 

Whether attending or not, **anyone can comment on this issue prior to the meeting to suggest topics or to add comments on planned topics or proposals**.

Meetings take place over Zoom: [https://zoom.us/j/91426197903?pwd=cjNGcjgzWmRqZ1YyRW9PM3FFNFVFUT09](https://zoom.us/j/91426197903?pwd=cjNGcjgzWmRqZ1YyRW9PM3FFNFVFUT09)

### Accessibility & Etiquette
* Participants must abide by our [Code-of-Conduct](https://github.com/OAI/Arazzo-Specification?tab=coc-ov-file#code-of-conduct).

* Meetings are not yet recorded -- this is something we're looking to get in place for on-demand viewing for those not able to attend.

* We invite you to feel comfortable to challenge any language or behaviour that is harmful or not inclusive during this meeting.

* We look forward to your participation, but please consider these acts of etiquette:
  * Remain on mute when not speaking to prevent interruptions.
  * Blur your background to reduce visual distractions.
  * Use the Zoom meeting "Raise Hand" feature to notify the group when you wish to speak.

| Blur My Background | Raise Hand |
|-|-|
| <img width="323" alt="Screenshot of Zoom UI showing the 'Stop Video' and 'Blur My Background' control" src="https://github.com/OAI/OpenAPI-Specification/assets/7367/7e43dbbb-6529-46e6-8b04-4c1aa852d9dd"> | <img width="323" alt="Screenshot of Zoom UI showing the 'Reaction' and 'Raise Hand' control" src="https://github.com/OAI/OpenAPI-Specification/assets/7367/f991722f-4651-40aa-9bc4-7e9a2a165a6a"> |

### Agenda Structure

| Topic | Owner | Decision/NextStep |
|-|-|-|
Intros and governance meta-topics (5 mins) | TDC / Arazzo maintainers | |
Any other business (add comments below to suggest topics) | TDC / Arazzo maintainers | |
[Approved spec PRs](https://github.com/OAI/Arazzo-Specification/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved) | Arazzo maintainers| |
[Active Projects](https://github.com/OAI/Arazzo-Specification/projects?query=is%3Aopen) | Arazzo maintainers | |
[New issues needing attention](https://github.com/search?q=repo%3Aoai%2Farazzo-specification+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) | Arazzo maintainers  | |

/cc [@OAI/tsc](https://github.com/orgs/OAI/teams/tsc) please suggest items for inclusion if applicable.

**Comment by frankkilcommins** [comment]
#260 is also ready for review/merge

**Comment by orubel** [comment]
@frankkilcommins I'm assuming there were no problems with the push request then?

**Comment by frankkilcommins** [comment]
@orubel I'll try to get to it tonight or tomorrow morning. I used a version of it above, so the work already added value. There were a few changes I made to fit with Arazzo on the fly. I'll suggest those modifications in the PR.

**Comment by orubel** [comment]
@frankkilcommins well since you have already adopted a version, you just have to add in your changes and we are done. Consider this a 'test in production' :)
