### ISSUE TITLE
both internal/external redirection need addressed

### ISSUE THREAD

**Issue by orubel** [OAI/Arazzo-Specification#277]
As Roy Fielding said, 'Internal redirection' does exist and has for many years in api applications.

We need to address this to **PLAN FOR SUCCESS**!!!

**Comment by orubel** [comment]
are we going to **Plan for success** by addressing this?

**Comment by darrelmiller** [comment]
As a notice community members, I am closing this issue to prevent further discussion on this topic.  We have unfortunately not found a way of working with Owen in a constructive and healthy manner.
