### ISSUE TITLE
Create dedicated preamble for the pretty print site specification

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/Arazzo-Specification#42]
Work with @MikeRalphson to create a dedicated preamble for the _pretty print_ version of the specification which will be housed on https://spec.openapis.org/

**Draft version:** https://mikeralphson.github.io/OpenAPI-Specification/workflows/1.0.0.html
**To resolve:** hardcoding related to the OpenAPI specification
**TBD:** Editors section

**Comment by MikeRalphson** [comment]
👀 on. Happy to review or help draft.

**Comment by shaisachs** [comment]
Relevant code is here - https://github.com/OAI/OpenAPI-Specification/blob/main/scripts/md2html/md2html.js#L83-L104

**Comment by frankkilcommins** [comment]
@MikeRalphson any time to jam on this in the near future?
